############################
# --- Setting 
############################
title: Sayako Kodera
author: Sayako Kodera #-> shown in the fotter
lang: "en-us"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

###############################################
# --- List of links in the navigation bar --- #
###############################################
navbar-links:
  About Me: "aboutme"
  #CV:

####################################
# --- Layout + General options --- #
####################################

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  linkedin: true

title-on-all-pages: true     # add the website title to the title of every page
feed_show_excerpt: false     # show article excerpts on the home page
# feed_show_tags: false      # show a list of tags below each post preview in the feed page
post_search: true            # add a search button to the navbar
edit_page_button: true       # add a button in the footer to edit the current page
navbar-var-length: false     # False -> second-level navigation menu items can be longer than the top-level menu

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap 

######################################
# --- Colours in CSS #
######################################
page-col: "#FFFFFF"
text-col: '#2D2B27' #"#404040"
link-col: "#008AFF" #= teal
hover-col: "#0085A1"
#navbar-col: "#EAEAEA" #= pale gray
navbar-text-col: "#404040" # = charcoal
navbar-border-col: "#DDDDDD" # = pale gray, little darker than EAEAEA
footer-col: "#EAEAEA" # = pale gray
footer-text-col: "#777777" # = dark gray
footer-link-col: "#404040" # = charcoal
footer-hover-col: "#0085A1" #= teal

# link-col:  
# hover-col: 
navbar-col: "#FAEBD7" # = beige
# navbar-text-col: '#2D2B27'
# navbar-border-col: '#2D2B27'
# footer-col: "#E3D8C4'
# footer-text-col: "#777777"
# footer-link-col: '#2D2B27' 
# footer-hover-col: "#0085A1"


################
# --- Misc --- #
################

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"


#####################################
# --- Footer social media links --- #
#####################################

# Select the social network links that you want to show in the footer.
# You can change the order that they show up on the page by changing the order here.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: sayako.kodera@izfp.fraunhofer.de
  # github: sayakokodera
#  ORCID: your ORCID ID
  google-scholar: Sayako Kodera

#################################################################################
# --- You don't need to touch anything below here (but you can if you want) --- #
#################################################################################

# Output options (more information on Jekyll's site)
timezone: "Germany"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

