############################
# --- Setting 
############################
title: Sayako Kodera
author: Sayako Kodera #-> shown in the fotter
lang: "en-us"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  About Me: "aboutme"
  #CV:
    

#####################################
# --- Footer social media links --- #
#####################################

# Select the social network links that you want to show in the footer.
# You can change the order that they show up on the page by changing the order here.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: sayako.kodera@izfp.fraunhofer.de
  github: sayakokodera
#  ORCID: your ORCID ID
  google-scholar: Sayako Kodera

###########################
# --- General options --- #
###########################

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  linkedin: true
# Add the website title to the title of every page
title-on-all-pages: true
# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: false
# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: false
# Add a search button to the navbar
post_search: true
# Add a button in the footer to edit the current page. Only works if your website is hosted on GitHub
edit_page_button: true
# Allow sub-menu items (second-level navigation menu items) to be longer than the top-level menu
navbar-var-length: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap 

######################################
# --- Layout
######################################

######################################
# --- Colours / background image --- #
######################################
page-col: "#FFFFFF"
text-col: '#2D2B27' #"#404040"
# link-col: "#008AFF"
# hover-col: "#FFFFFF"
# navbar-col: '#2D2B27'
# navbar-text-col: '#2D2B27' #"#404040"
# navbar-border-col: '#2D2B27'#"#DDDDDD"
# footer-col: "#E3D8C4' #"#EAEAEA"
# footer-text-col: "#777777"
# footer-link-col: '#2D2B27' #"#404040"
# footer-hover-col: "#0085A1"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

################
# --- Misc --- #
################

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"


#################################################################################
# --- You don't need to touch anything below here (but you can if you want) --- #
#################################################################################

# Output options (more information on Jekyll's site)
timezone: "Germany"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

